CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) NOT NULL DEFAULT '',  `slug` varchar(200) NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=MyISAM AUTO_INCREMENT=64 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('3', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('4', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('5', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('6', 'Adverisement', 'adverisement', '0');
INSERT INTO `wp_terms` VALUES('7', 'Hobbies', 'hobbies', '0');
INSERT INTO `wp_terms` VALUES('8', 'Technology', 'technology', '0');
INSERT INTO `wp_terms` VALUES('9', 'beauty', 'beauty', '0');
INSERT INTO `wp_terms` VALUES('10', 'Childhood', 'childhood', '0');
INSERT INTO `wp_terms` VALUES('11', 'church', 'church', '0');
INSERT INTO `wp_terms` VALUES('12', 'depressive', 'depressive', '0');
INSERT INTO `wp_terms` VALUES('13', 'first', 'first', '0');
INSERT INTO `wp_terms` VALUES('14', 'friendship', 'friendship', '0');
INSERT INTO `wp_terms` VALUES('15', 'impression', 'impression', '0');
INSERT INTO `wp_terms` VALUES('16', 'is coming', 'is coming', '0');
INSERT INTO `wp_terms` VALUES('17', 'likeit', 'likeit', '0');
INSERT INTO `wp_terms` VALUES('18', 'School', 'school', '0');
INSERT INTO `wp_terms` VALUES('19', 'surfing car', 'surfing car', '0');
INSERT INTO `wp_terms` VALUES('20', 'upset', 'upset', '0');
INSERT INTO `wp_terms` VALUES('21', 'whatswrongtome', 'whatswrongtome', '0');
INSERT INTO `wp_terms` VALUES('22', 'wordpress', 'wordpress', '0');
INSERT INTO `wp_terms` VALUES('23', 'wtfimdoin?', 'wtfimdoin', '0');
INSERT INTO `wp_terms` VALUES('24', 'Leave Management', 'leave-management', '0');
INSERT INTO `wp_terms` VALUES('51', 'Module', 'module', '0');
INSERT INTO `wp_terms` VALUES('26', 'Time And Attendance Management', 'time-and-attendance-management', '0');
INSERT INTO `wp_terms` VALUES('52', 'Footer_module2', 'footer_module2', '0');
INSERT INTO `wp_terms` VALUES('28', 'Payroll Management', 'payroll-management', '0');
INSERT INTO `wp_terms` VALUES('30', 'Employee Management', 'employee-management', '0');
INSERT INTO `wp_terms` VALUES('31', 'Exit Management', 'exit-management', '0');
INSERT INTO `wp_terms` VALUES('32', 'Helpdesk', 'helpdesk', '0');
INSERT INTO `wp_terms` VALUES('33', 'Performance Management', 'performance-management', '0');
INSERT INTO `wp_terms` VALUES('34', 'Recruitment', 'recruitment-management', '0');
INSERT INTO `wp_terms` VALUES('35', 'Intranet Portal', 'intranet-portal', '0');
INSERT INTO `wp_terms` VALUES('36', 'Footer menu', 'footer-menu', '0');
INSERT INTO `wp_terms` VALUES('37', 'Primary menu', 'primary-menu', '0');
INSERT INTO `wp_terms` VALUES('38', 'Conference Room Booking', 'conference-room-booking', '0');
INSERT INTO `wp_terms` VALUES('39', 'Timesheet', 'timesheet', '0');
INSERT INTO `wp_terms` VALUES('40', 'Task Management', 'task-management', '0');
INSERT INTO `wp_terms` VALUES('41', 'Travel and Expense', 'travel-and-expense', '0');
INSERT INTO `wp_terms` VALUES('42', 'Training', 'training', '0');
INSERT INTO `wp_terms` VALUES('43', 'Document Management System', 'document-management-system', '0');
INSERT INTO `wp_terms` VALUES('44', 'Visitor Management', 'visitor-management', '0');
INSERT INTO `wp_terms` VALUES('45', 'Projects Management', 'projects-management', '0');
INSERT INTO `wp_terms` VALUES('53', 'Footer_menu3', 'footer_menu3', '0');
INSERT INTO `wp_terms` VALUES('47', 'main menu', 'main-menu', '0');
INSERT INTO `wp_terms` VALUES('49', 'Footer_module1', 'footer_module1', '0');
INSERT INTO `wp_terms` VALUES('54', 'Leave', 'leave', '0');
INSERT INTO `wp_terms` VALUES('55', 'Intranet', 'intranet', '0');
INSERT INTO `wp_terms` VALUES('56', 'Payroll', 'payroll', '0');
INSERT INTO `wp_terms` VALUES('57', 'Performance', 'performance', '0');
INSERT INTO `wp_terms` VALUES('58', 'Intranet', 'intranet', '0');
INSERT INTO `wp_terms` VALUES('59', 'Leave', 'leave', '0');
INSERT INTO `wp_terms` VALUES('60', 'Payroll', 'payroll', '0');
INSERT INTO `wp_terms` VALUES('61', 'ISRI Menu', 'isri-menu', '0');
INSERT INTO `wp_terms` VALUES('62', 'Imp Links', 'imp-links', '0');
INSERT INTO `wp_terms` VALUES('63', 'About Us', 'about-us', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
